if: branch = master OR tag is present

env:
  global:
    - CODECOV_TOKEN=$CODECOV_TOKEN
    - GROOVY_TURN_OFF_JAVA_WARNINGS=true

language: java
jdk:
  - openjdk11

before_script:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

sudo: required
services:
  - docker

install:
  - ./gradlew build -x check --no-daemon

jobs:
  include:
    - stage: integration-test
      env: [ NAME=core ]
      script:
        - ./gradlew integrationTest --no-daemon
        - ./gradlew codeCoverageReport

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)