if: branch = master OR tag is present

language: java
jdk:
  - oraclejdk11

before_script:
  - chmod +x gradlew
  - GROOVY_TURN_OFF_JAVA_WARNINGS=true

env:
  global:
    - CODECOV_TOKEN=$CODECOV_TOKEN

sudo: required
services:
  - docker

install:
  - ./gradlew build -x check --no-daemon

jobs:
  include:
    - stage: test
      env: [ NAME=core ]
      script:
        - ./gradlew integrationTest --no-daemon

#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)