spring:
  profiles:
    active: test
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

logging:
  level:
    root: WARN
    org:
      hibernate: INFO
      springframework:
        web: WARN
