spring:
  profiles:
    active: integration-test
  flyway:
    enabled: true
    locations: classpath:/db/migration #,classpath:/db/testdata
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    root: WARN
    org:
      testcontainers: DEBUG
      flywaydb: WARN
      hibernate: INFO
    com:
      github:
        dockerjava: DEBUG