spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/likeapro?useUnicode=yes&characterEncoding=UTF-8
    username: likeapro_user
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    root: WARN
    org:
      hibernate: WARN
      springframework:
        web: WARN