spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/likeapro?useUnicode=yes&characterEncoding=UTF-8
    username: likeapro_user
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 3
      minimum-idle: 10000
      connection-timeout: 10000
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    root: WARN
    org:
      hibernate: INFO
      springframework:
        web: WARN
