name: Like a pro CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    container:
      image: gradle:jdk11
      volumes:
        - $PWD:$PWD
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run tests
        run: gradle test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./build/jacoco/test.exec
          flags: unittests
          name: codecov-umbrella
